USE STG_Bank
DELETE FROM STG_TREASURY_PRODUCTS WHERE 1=1;
DELETE FROM STG_DEPOSIT WHERE 1=1;
DELETE FROM STG_Credit_Card WHERE 1=1;
DELETE FROM STG_LOAN WHERE 1=1;
DELETE FROM STG_PAYMENT WHERE 1=1;
DELETE FROM STG_TRANSACTIONS WHERE 1=1;
DELETE FROM STG_TRANSFER WHERE 1=1;
DELETE FROM STG_WITHDRAWAL WHERE 1=1;
DELETE FROM STG_Branch WHERE 1=1;
DELETE FROM STG_Account WHERE 1=1;
DELETE FROM STG_TRANSACTION_TYPE WHERE 1=1;
DELETE FROM STG_Customers WHERE 1=1;


Select * FROM STG_Account WHERE 1=1;
Select * FROM STG_Branch WHERE 1=1; 
Select * FROM STG_Customers WHERE 1=1;
Select * FROM STG_Credit_Card WHERE 1=1;
Select * FROM STG_LOAN WHERE 1=1;
Select * FROM STG_DEPOSIT WHERE 1=1;
Select * FROM STG_PAYMENT WHERE 1=1;
Select * FROM STG_TRANSACTION_TYPE WHERE 1=1;
Select * FROM STG_TRANSACTIONS WHERE 1=1;
Select * FROM STG_TRANSFER WHERE 1=1;
Select * FROM STG_TREASURY_PRODUCTS WHERE 1=1;
Select * FROM STG_WITHDRAWAL WHERE 1=1;
